name: geoprofile
channels:
  - conda-forge
dependencies:
  - black
  - contextily
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - matplotlib
  - numpy
  - panel
  - pyepsg
  - rasterio
  - richdem
  - rioxarray
  - shapely
  - xarray
  - pip
  - pip:
    - "git+https://github.com/friedrichknuth/driveanon.git#egg=driveanon"
    - "git+https://github.com/GlacioHack/GeoUtils.git#egg=GeoUtils"
    - "git+https://github.com/GlacioHack/xdem.git#egg=xdem"
    